git_account_name = "stanislav-zhurich"
git_branch_name = "test-1"
git_repository_name = "azure-big-data-reference-architecture"
git_root_folder = "/datafactory"
git_root_synapse_folder = "/synapse"
git_url = "https://github.com"